vendor in new ocamlfind

diff --git a/local-packages/ocamlfind/configure b/local-packages/ocamlfind/configure
--- a/local-packages/ocamlfind/configure
+++ b/local-packages/ocamlfind/configure
@@ -7,7 +7,12 @@
 
 #set -x
 
-version="1.8.1"
+version="$(sed -ne 's/^version: *"\(.*\)\.git".*/\1/p' opam)"
+
+if test -z "$version"; then
+  echo "Internal error: failed to parse version number from opam file" 1>&2
+	exit 1
+fi
 
 # Remember the old IFS value:
 oldifs="$IFS"
@@ -71,7 +76,7 @@ get_lib () {
     # $2...: places to test
     libname="$1"
     while [ "$#" != "0" ]; do
-	if [ -f "$1/lib${libname}.so" -o -f "$1/lib${libname}.a" ]; then
+	if [ -f "$1/lib${libname}.so" ] || [ -f "$1/lib${libname}.a" ]; then
 	    echo "$1"
 	    return 0
 	fi
@@ -184,7 +189,7 @@ echo "Configuring core..."
 
 # Some standard Unix tools must be available:
 
-for tool in sed ocaml ocamlc uname rm make cat m4 dirname basename; do
+for tool in sed ocaml ocamlc uname rm make cat dirname basename; do
     if in_path $tool; then true; else
 	echo "configure: $tool not in PATH; this is required" 1>&2
 	exit 1
@@ -296,16 +301,16 @@ d="$ocaml_core_bin"
 while [ "$d" != '/' ]; do
     f=0
     if [ -d "$d/man/man1" ]; then
-	if [ -f "$d/man/man1/ocamlc.1" -o \
-	     -f "$d/man/man1/ocamlc.1.gz" -o \
-	     -f "$d/man/man1/ocamlc.1.Z" ]; then
+	if [ -f "$d/man/man1/ocamlc.1" ] ||
+	   [ -f "$d/man/man1/ocamlc.1.gz" ] ||
+	   [ -f "$d/man/man1/ocamlc.1.Z" ]; then
 	     f=1
 	fi
     else
 	if [ -d "$d/man/mann" ]; then
-	    if [ -f "$d/man/mann/ocamlc.n" -o \
-		 -f "$d/man/mann/ocamlc.n.gz" -o \
-		 -f "$d/man/mann/ocamlc.n.Z" ]; then
+	    if [ -f "$d/man/mann/ocamlc.n" ] ||
+		   [ -f "$d/man/mann/ocamlc.n.gz" ] ||
+		   [ -f "$d/man/mann/ocamlc.n.Z" ]; then
 		f=1
 	    fi
 	fi
@@ -367,7 +372,7 @@ if ocamlc -config >/dev/null 2>/dev/null; then
 else
     # Old ocamlc do not have -config.
     rm -f itest-aux/simple
-    ocamlc -w a -custom -thread -o itest-aux/simple unix.cma threads.cma itest-aux/simple_threads.ml \
+    ocamlc -w a -custom -thread -o itest-aux/simple -I +unix unix.cma threads.cma itest-aux/simple_threads.ml \
 	>itest-aux/err.out 2>&1
     output=`cat itest-aux/err.out`
 
@@ -379,8 +384,8 @@ fi
 ######################################################################
 # Does this version of OCaml support autolinking?
 
-# Works for O'Caml >= 3.00 on. Because findlib can only be compiled
-# with these O'Caml versions, we can safely assume that autolinking
+# Works for OCaml >= 3.00 on. Because findlib can only be compiled
+# with these OCaml versions, we can safely assume that autolinking
 # is enabled.
 
 ocaml_autolink="true"
@@ -392,7 +397,7 @@ echo "Testing DLLs..."
 
 have_dlls="yes"
 
-ocaml unix.cma itest-aux/simple.ml >/dev/null || have_dlls="no"
+ocaml -I +unix unix.cma itest-aux/simple.ml >/dev/null || have_dlls="no"
 
 ######################################################################
 # Does this version of OCaml support extension points?
@@ -418,19 +423,135 @@ ocamlc -opaque >/dev/null 2>/dev/null || opaque=""
 ######################################################################
 # Configure libraries
 
+check_before_install=0
+findlib_installed_meta=''
+if [ -d "${ocaml_sitelib}" ]; then
+    previous_config="${ocaml_sitelib}/findlib/Makefile.packages"
+    if [ -f "${previous_config}" ]; then
+        echo "Querying installation: found list of findlib-generated META files"
+        eval "$(sed -ne 's/ /,/g' -e 's/^SITELIB_META,*=,*\([^,].*[^,]\),*/findlib_installed_meta="\1"/p' "$previous_config")"
+        echo "Installation has: $findlib_installed_meta"
+    else
+        previous_config=''
+        check_before_install=1
+        echo "Querying installation: META list not found"
+        echo "make install will double-check installed META files"
+    fi
+else
+    previous_config=''
+fi
+
 echo "Configuring libraries..."
 
-# Check whether Bigarray is present.
+# Only succeeds if ${ocaml_sitelib}/$1/META exists and we're **certain**
+# it wasn't installed by a previous findlib installation.
+is_third_party_META () {
+    if [ $check_before_install -eq 0 ]; then
+        if [ -f "${ocaml_sitelib}/$1/META" ]; then
+            case ",$findlib_installed_meta," in
+                *,$1,*)
+                    return 1;;
+                *)
+                return 0;;
+            esac
+        else
+            return 1
+        fi
+    else
+        return 1
+    fi
+}
 
-lbigarray=bigarray
-# always
+check_library () {
+    if is_third_party_META $1; then
+        echo "$1: package already present"
+        # Library is present - exit code is 0 because the library is found
+        # (e.g. detection for Unix) but we don't actually add it to the
+        # generated_META list.
+        return 0
+    fi
+
+    if [ -z "$3" ]; then
+        check_library "$1" "$2" "$1.cmi"
+        return $?
+    fi
+
+    package="$1"
+    if [ -z "$2" ]; then
+        msg=''
+    else
+        msg=" ($2)"
+    fi
+
+    shift 2
+    for file; do
+        if [ -e "${ocaml_core_stdlib}/${file}" ]; then
+            package_dir="$(dirname "${file}")"
+            if [ "${package_dir}" = '.' ]; then
+                echo "${package}: found"
+                package_subdir='.'
+                package_dir='^'
+            else
+                package_subdir="${package_dir}"
+                package_dir="+${package_dir}"
+                echo "${package}: found (in ${package_dir})"
+            fi
+            package_key="$(echo "${package}" | tr - _)"
+            eval "${package_key}_dir=\"${package_dir}\""
+            eval "${package_key}_subdir=\"${package_subdir}\""
+            if [ "$package" = 'num' ]; then
+                generated_META="${generated_META} num num-top"
+                numtop='num-top'
+            else
+                generated_META="${generated_META} ${package}"
+            fi
+            return 0
+        fi
+    done
+
+    echo "$package: not present${msg}"
+    return 1
+}
+
+generated_META='stdlib'
+numtop=''
+
+if ! check_library unix 'possible since 4.08' unix/unix.cmi unix.cmi; then
+    echo "configure: ocamlfind requires OCaml's Unix library" 1>&2
+    exit 1
+fi
+
+check_library dynlink '' dynlink/dynlink.cmi dynlink.cmi
+check_library bigarray 'possible since 4.08'
+check_library compiler-libs '' 'compiler-libs'
+check_library dbm 'normal since 4.00'
+check_library graphics 'normal since 4.09'
+check_library num 'normal since 4.06'
+check_library ocamlbuild 'normal since 4.03' ocamlbuild/ocamlbuildlib.cma
+check_library ocamldoc '' ocamldoc/odoc.cmi
+check_library raw_spacetime 'normal since 4.12' raw_spacetime_lib.cmxa
+check_library threads '' threads/thread.cmi vmthreads/thread.cmi;
+check_library runtime_events '' runtime_events/runtime_events.cmi
+
+# Need to know if str and labltk are available for the toolbox
+if check_library str 'possible since 4.08' str/str.cmi str.cmi; then
+    have_str=1
+else
+    have_str=0
+fi
+
+if check_library labltk 'normal since 4.02' labltk/labltk.cma; then
+    have_labltk=1
+else
+    have_labltk=0
+fi
 
 # Dynlink check.
 
 have_natdynlink=0
 natdynlink=""
 camlp4_dynlink=""
-if [ -f "${ocaml_core_stdlib}/dynlink.cmxa" ]; then
+if [ -f "${ocaml_core_stdlib}/${dynlink_subdir}/dynlink.cmxa" ]; then
     have_natdynlink=1
     natdynlink="archive(native) = \"dynlink.cmxa\""
     camlp4_dynlink="dynlink"
@@ -440,36 +561,14 @@ else
     echo "native dynlink: not found"
 fi
 
-# Check whether labltk is present.
-
-if [ -f "${ocaml_core_stdlib}/labltk/labltk.cma" ]; then
-    llabltk=labltk
-    echo "labltk: found"
-else
-    llabltk=''
-    echo "labltk: not present"
-    if [ $with_toolbox -gt 0 ]; then
-	echo "Sorry, toolbox requires labltk - omitting toolbox."
-    fi
-    with_toolbox=0
-fi
-
-# Check whether ocamlbuild is present
-
-if [ -f "${ocaml_core_stdlib}/ocamlbuild/ocamlbuildlib.cma" ]; then
-    lobuild=ocamlbuild
-    echo "ocamlbuild: found"
-else
-    lobuild=""
-    echo "ocamlbuild: not present"
-fi
-
 # Check on camlp4:
 
 if [ $with_camlp4 -eq 0 ]; then
-    lcamlp4=''
     echo "camlp4: disabled"
 else if in_path camlp4; then
+    if is_third_party_META camlp4; then
+        echo "camlp4: third-party"
+    fi
     camlp4_dir=`camlp4 -where | tr -d '\015'`
     if [ ${use_cygpath} -gt 0 ]; then
 	camlp4_dir=`echo x | env USE_CYGPATH=1 tools/patch x "$camlp4_dir"`
@@ -490,120 +589,76 @@ else if in_path camlp4; then
     else
 	camlp4style=309
     fi
-    lcamlp4="camlp4"
+    generated_META="${generated_META} camlp4"
     rm -rf "site-lib-src/camlp4"
     mkdir "site-lib-src/camlp4"
     cp "site-lib-src/camlp4.$camlp4style/META.in" "site-lib-src/camlp4/"
     echo "camlp4: using $camlp4_cmd, style $camlp4style"
 else
-    lcamlp4=''
     with_camlp4=0
     echo "camlp4: not present (normal since OCaml-4.02)"
 fi
 fi
 
-# compiler-libs?
-if [ -d "${ocaml_core_stdlib}/compiler-libs" ]; then
-    echo "compiler-libs: found"
-    lcomplibs="compiler-libs"
-else
-    echo "compiler-libs: not present"
-    lcomplibs=""
-fi
-
-# dbm?
-
-if [ -f "${ocaml_sitelib}/dbm/META" ]; then
-    echo "dbm: package already present"
-    ldbm=""
-elif [ -f "${ocaml_core_stdlib}/dbm.cmi" ]; then
-    echo "dbm: found"
-    ldbm="dbm"
-else
-    echo "dbm: not present (normal since OCaml-4.00)"
-    ldbm=""
-fi
-
-# num?
-
-if [ -f "${ocaml_sitelib}/num/META" ]; then
-    echo "num: package already present"
-    lnum=""
-    numtop=""
-elif [ -f "${ocaml_core_stdlib}/num.cmi" ]; then
-    echo "num: found but not as package"
-    lnum="num num-top"
-    numtop="num-top"
-else
-    echo "num: not present (normal since OCaml-4.06)"
-    lnum=""
-    numtop=""
-fi
-
 # bytes?
+# (NB. This is always ours, and it doesn't go into generated_META)
 
-if [ -f "${ocaml_core_stdlib}/bytes.cmi" -o \
-     -f "${ocaml_core_stdlib}/stdlib__bytes.cmi" ]; then
+req_bytes=""
+if [ -f "${ocaml_core_stdlib}/bytes.cmi" ] ||
+   [ -f "${ocaml_core_stdlib}/stdlib__bytes.cmi" ] ||
+   [ -f "${ocaml_core_stdlib}/stdlib__Bytes.cmi" ]; then
     echo "bytes: found, installing fake library"
     lbytes="bytes"
     cbytes=0
 else
     echo "bytes: not found, installing compat library"
     lbytes=""
+    req_bytes="bytes"
     cbytes=1
 fi
 
-# spacetime?
 
-if [ -f "${ocaml_core_stdlib}/raw_spacetime_lib.cmxa" ]; then
-    echo "spacetime: found"
-    lspacetime="raw_spacetime"
-else
-    echo "spacetime: not found"
-    lspacetime=""
+if [ $with_toolbox -gt 0 ]; then
+    if [ $have_str -eq 0 ] || [ $have_labltk -eq 0 ]; then
+	echo "Sorry, toolbox requires str and labltk - omitting toolbox."
+        with_toolbox=0
+    fi
 fi
-
-# graphics?
-
-if [ -f "${ocaml_core_stdlib}/graphics.cmi" ]; then
-    echo "graphics: found"
-    lgraphics="graphics"
-else
-    echo "graphics: not found"
-    lgraphics=""
-fi
-
 
 # Generate the META files now.
-
-l="$ldbm dynlink $lgraphics $lnum str threads unix stdlib bigarray ocamldoc $llabltk $lcamlp4 $lobuild $lcomplibs $lbytes $lspacetime"
 
 for dir in site-lib-src/*; do
     # We do not really know if $dir is a directory.
     rm -f $dir/META
 done
 
-for lib in $l; do
+for lib in $generated_META $lbytes; do
     if=""
     if [ -f site-lib-src/$lib/interfaces.out ]; then
 	if=`cat site-lib-src/$lib/interfaces.out`
     fi
-    m4 -Dos=$os \
-	"-Dtype_of_threads=${ocaml_threads}" \
-	"-Dcamlp4_dir=${camlp4_dir}" \
-	"-Dcamlp4_version=${camlp4_version}" \
-	"-Dcamlp4_cmd=${camlp4_cmd}" \
-	"-Dcamlp4_dynlink=${camlp4_dynlink}" \
-	"-Dinterfaces=${if}" \
-	"-Dfindlib_version=${version}" \
-	"-Dnatdynlink=${natdynlink}" \
-	site-lib-src/$lib/META.in >site-lib-src/$lib/META
+    sed -e "s|%%os%%|${os}|g" \
+        -e "s|%%type_of_threads%%|${ocaml_threads}|g" \
+        -e "s|%%camlp4_dir%%|${camlp4_dir}|g" \
+        -e "s|%%camlp4_version%%|${camlp4_version}|g" \
+        -e "s|%%camlp4_cmd%%|${camlp4_cmd}|g" \
+        -e "s|%%camlp4_dynlink%%|${camlp4_dynlink}|g" \
+        -e "s|%%interfaces%%|${if}|g" \
+        -e "s|%%findlib_version%%|${version}|g" \
+        -e "s|%%natdynlink%%|${natdynlink}|g" \
+        -e "s|%%dynlink_dir%%|${dynlink_dir}|g" \
+        -e "s|%%unix_dir%%|${unix_dir}|g" \
+        -e "s|%%str_dir%%|${str_dir}|g" \
+        site-lib-src/$lib/META.in > site-lib-src/$lib/META
+
     echo "Configuration for $lib written to site-lib-src/$lib/META"
 done
 
 for part in `cd src; echo *`; do
     if [ -f "src/$part/META.in" ]; then
-	sed -e "s/@VERSION@/$version/g" src/$part/META.in >src/$part/META
+	sed -e "s/@VERSION@/$version/g" \
+            -e "s/@REQUIRES@/${req_bytes}/g" \
+            src/$part/META.in >src/$part/META
     fi
 done
 
@@ -631,11 +686,16 @@ fi
 # Write Makefile.config
 
 parts="findlib"
+ocamlfind_ocamlflags="-I +unix -I +dynlink"
+ocamlfind_archives="findlib.cma unix.cma"
 if [ $with_toolbox -gt 0 ]; then
     parts="$parts findlib-toolbox"
 fi
 if [ $cbytes -gt 0 ]; then
-    parts="$parts bytes"
+    # bytes first, because findlib needs it
+    parts="bytes $parts"
+    ocamlfind_ocamlflags="${ocamlfind_archives} -I ../bytes"
+    ocamlfind_archives="bytes.cma ${ocamlfind_archives}"
 fi
 
 echo "# Makefile.config written by configure" >Makefile.config
@@ -647,6 +707,8 @@ echo "OCAML_THREADS=${ocaml_threads}" >>Makefile.config
 echo "OCAMLFIND_BIN=${ocamlfind_bin}" >>Makefile.config
 echo "OCAMLFIND_MAN=${ocamlfind_man}" >>Makefile.config
 echo "OCAMLFIND_CONF=${ocamlfind_config}" >>Makefile.config
+echo "OCAMLFIND_OCAMLFLAGS=${ocamlfind_ocamlflags}" >>Makefile.config
+echo "OCAMLFIND_ARCHIVES=${ocamlfind_archives}" >>Makefile.config
 echo "OCAML_AUTOLINK=${ocaml_autolink}" >>Makefile.config
 echo "OCAML_REMOVE_DIRECTORY=${have_remdir}" >>Makefile.config
 echo "EXEC_SUFFIX=${exec_suffix}" >>Makefile.config
@@ -654,7 +716,6 @@ echo "LIB_SUFFIX=${lib_suffix}" >>Makefile.config
 echo "CUSTOM=${custom}" >>Makefile.config
 echo "PARTS=${parts}" >>Makefile.config
 echo "INSTALL_TOPFIND=${with_topfind}" >>Makefile.config
-echo "INSTALL_CAMLP4=${with_camlp4}" >>Makefile.config
 echo "USE_CYGPATH=${use_cygpath}" >>Makefile.config
 echo "HAVE_NATDYNLINK=${have_natdynlink}" >>Makefile.config
 echo "VERSION=${version}" >>Makefile.config
@@ -667,6 +728,12 @@ if [ "$mingw_lib" != "" ]; then
     echo "OCAMLOPT_FLAGS=-I \"${mingw_lib}\"" >>Makefile.config
 fi
 echo "OPAQUE=${opaque}" >>Makefile.config
+echo "CHECK_BEFORE_INSTALL=${check_before_install}" >>Makefile.config
+echo "INSTALLDIR = install -d" >>Makefile.config
+echo "# change to INSTALLDIR = mkdir -p   when BSD install is unavavailable" >>Makefile.config
+echo "INSTALLFILE = install -c" >>Makefile.config
+echo "# change to INSTALLFILE = cp   when BSD install is unavailable" >>Makefile.config
+echo "SITELIB_META=${generated_META}" >Makefile.packages
 
 # All OK
 
@@ -718,3 +785,4 @@ echo
 echo "Configuration has been written to Makefile.config"
 echo
 echo "You can now do 'make all', and optionally 'make opt', to build ocamlfind."
+
